name: Docker scan

on:
  workflow_dispatch:

jobs:
  docker-push:
    name: Scan image
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: version
        run: |
          echo "contents<<VERSIONEOF" >> $GITHUB_OUTPUT
          basename "$GITHUB_REF" >> $GITHUB_OUTPUT
          echo "VERSIONEOF" >> $GITHUB_OUTPUT

      - name: Scan image
        id: scan
        uses: anchore/scan-action@v6
        with:
          image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.contents }}

      - name: Print report
        run: cat ${{ steps.scan.outputs.sarif }}

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
